name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - uses: actions/checkout@v2
    - run: go build -v ./...
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: go-app
